MAX_SHORTCUTS = 500;
MAX_CHARACTERS = 98000;
CURRENT_SHORTCUTS = 0;
CURRENT_CHARACTERS = 0;
SHORTCUT_OVERHEAD = 48;
BYTE_MULTIPLIER = 4;
STORAGE_KEY = "EASY_ACCENTS_STORAGE_COUNT";
DEFAULT_SHORTCUT_COUNT = 1;
DEFAULT_CHARACTER_COUNT = 65;

SHORTCUTS = {};
TIME_CREATED = {};
